apiVersion: apps/v1
kind: Deployment
metadata:
  name: joao-marcos-api-recommendation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joao-marcos-api-recommendation
  template:
    metadata:
      labels:
        app: joao-marcos-api-recommendation
    spec:
      volumes:
        - name: project2-pv-joaodepollo
          persistentVolumeClaim:
            claimName: project2-pv-joaodepollo
      containers:
        - name: joao-marcos-api-recommendation
          image:  joaovitorsd/api-tp-cloud-ml-prd:latest
          volumeMounts:
            - name: project2-pv-joaodepollo
              mountPath: /usr/src
          ports:
          - name: http
            containerPort: 8080
