apiVersion: v1
kind: Service
metadata:
  name: joao-marcos-api-recommendation-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.10
  selector:
    app: joao-marcos-api-recommendation
  ports:
    - protocol: TCP
      port: 32188
      targetPort: 8080
      nodePort: 32188
